export const faqsData = [
    {
        id: 1,
        question : "What types of powerful strategies does Sen-X offer?",
        answer: 'Sen-X provides a range of powerful strategies, including advanced digital marketing, cutting-edge software solutions, and innovative technology integrations. Our strategies are designed to drive business growth and ensure you stay ahead of the competition.',
    },
    { id: 2,
        question : "What sets Sen-X apart from other service providers?",
        answer: 'Our focus on redefining expectations sets us apart. We go beyond traditional approaches by offering cutting-edge technologies and a client-centered methodology that emphasizes innovation and exceptional results, ensuring your business stands out.',
    },
    { id: 3,
        question : "Can you provide examples of technologies used in your strategies?",
        answer: 'Yes, we utilize a range of advanced technologies including the latest in software development, data analytics, cybersecurity, and digital marketing tools. These technologies are selected based on their ability to drive innovation and achieve your business objectives.',
    },
    { id: 4,
        question : "What industries does Sen-X serve?",
        answer: 'We serve a variety of industries including technology, retail, finance, healthcare, and more. Our solutions are adaptable to meet the needs of different sectors.',
    },
    { id: 5,
        question : "Are there any initial costs or fees for starting with Sen-X?",
        answer: 'Initial costs or fees may vary depending on the services you choose. We provide detailed information and a transparent cost breakdown during the initial consultation.',
    },
    { id: 6,
        question : " How can I get started with Sen-X’s services?",
        answer: 'To get started, reach out to us through our website or contact our team directly. We will arrange an initial consultation to discuss your needs, explore how our strategies can benefit your business, and begin the process of developing a customized plan.',
    },
]