export const faqsData = [
    {
        id: 1,
        question : " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, vitae!",
        answer: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus cum nemo similique incidunt adipisci quas voluptatem reiciendis tempora temporibus quod!',
    },
    { id: 2,
        question : " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, vitae!",
        answer: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus cum nemo similique incidunt adipisci quas voluptatem reiciendis tempora temporibus quod!',
    },
    { id: 3,
        question : " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, vitae!",
        answer: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus cum nemo similique incidunt adipisci quas voluptatem reiciendis tempora temporibus quod!',
    },
    { id: 4,
        question : " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, vitae!",
        answer: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus cum nemo similique incidunt adipisci quas voluptatem reiciendis tempora temporibus quod!',
    },
    { id: 5,
        question : " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, vitae!",
        answer: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus cum nemo similique incidunt adipisci quas voluptatem reiciendis tempora temporibus quod!',
    },
    { id: 6,
        question : " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque, vitae!",
        answer: '  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus cum nemo similique incidunt adipisci quas voluptatem reiciendis tempora temporibus quod!',
    },
]